accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("follow/<int:user_id>/", views.follow, name="follow"),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path("",views.post_list, name="list"),
    path("<int:pk>/",views.post_detail, name="detail"),
    path("create/",views.create, name="create"),
    path("update/<int:pk>",views.update, name="update"),
    path("delete/<int:pk>",views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:pk>/check/", views.check, name="check"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('products.urls')),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField("self", related_name="followers", symmetrical=False)
    # symmetrical=False 짝사랑구현

products/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    price = models.PositiveIntegerField()
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    check_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="check_posts")

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    content = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('accounts:change_password')}")
            self.fields["password"].help_text = password_help_text

accounts/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import User


@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            #next_url = request.GET.get("next") or "post:list"
            return redirect("post:list")
    else:
        form = AuthenticationForm()

    context = {"form": form}
    return render(request, "accounts/login.html", context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("post:list")


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("post:list")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect("post:list")


@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("post:list")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("post:list")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)

def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    context = {
        "check_posts": user.check_posts.all(),
        "profile_user": user,

    }
    return render(request, "accounts/profile.html", context)

def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if request.user != member:
            if request.user in member.followers.all():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("accounts:profile", member.id)
    return redirect("accounts:login")

accounts/templates/accounts/change_password.html
{% extends "base.html" %}


{% block content %}
<h1>비밀번호 변경</h1>

<form action="{% url "accounts:change_password" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 변경</button>
</form>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<br><h1>로그인</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input class="btn btn-outline-dark" type="submit" value="로그인">
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br><h1>{{ profile_user.username }}의 프로필 페이지</h1><br>
     <img src="{% static "accouts/user.png" %}" class="d-block w-15">

    <p> 자기 소개글 과 프로필사진 이 들어갈 공간</p>

    <p>회원가입 일 : {{ profile_user.date_joined }}</p>
    <p>e-mail : {{ profile_user.email_user }}</p>
    <p>팔로워 수 : {{ profile_user.followings.count}}</p>

    {% if request.user != member %}
        <form action="{% url "accounts:follow" profile_user.pk %}" method="POST">
            {% csrf_token %}
            {% if request.user in member.followers.all %}
                <input class="btn btn-outline-dark" type="submit" value="언팔로우">
            {% else %}
                <input class="btn btn-outline-dark" type="submit" value="팔로우">
            {% endif %}
        </form>
    {% endif %}
    <br><ul>
        <h2> 작성글 목록 </h2>
    {% for list in profile_user.post_set.all %}
       <br> <li>
            <a href="{% url "post:detail" list.id %}">
           <button class="btn btn-outline-dark"> {{ list.title }} </button>
            </a>
        </li>
    {% endfor %}

    </ul>


    <ul>
        <br><h2> 찜 목록 </h2><br>
    {% for checkpost in check_posts  %}
        <li>
            <a href="{% url "post:detail" checkpost.id %}">
            <button class="btn btn-outline-dark"> {{ checkpost.title }} : {{ checkpost.price }}원</button>
            </a>
        </li><br>
    {% endfor %}
    
    </ul>

    <a href="{% url "post:list" %}">홈으로 돌아가기</a>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>회원가입</h1>
    <form action="{% url "accounts:signup" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button>
    </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
    <h1>회원 정보 수정</h1>

    <form action="{% url "accounts:update" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">수정</button>
    </form>

{% endblock %}