accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("follow/<int:user_id>/", views.follow, name="follow"),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path("",views.post_list, name="list"),
    path("<int:pk>/",views.post_detail, name="detail"),
    path("create/",views.create, name="create"),
    path("update/<int:pk>",views.update, name="update"),
    path("delete/<int:pk>",views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:pk>/check/", views.check, name="check"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('products.urls')),
    path("accounts/", include("accounts.urls")),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>SPARTAMARKET_MADE_BY_HYun</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block head %}{% endblock head %}
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark"  >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "post:list" %}">Sparta market</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "accounts:profile" user.id %}"> My profile</a>
        </li>
            
            <div class="container-fluid">
         <li class="nav-item">
          <a class="nav-link"><form class="d-flex" action="{% url "accounts:delete" %}" method="POST">
                {% csrf_token %}
                <input  class="form-control me-2" type="submit" value="회원탈퇴"></input>
            </form></a>
        </div>
         
            
      <div class="container-fluid">
        <li class="nav-item">
          <a class="nav-link"><form class="d-flex" action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input class="form-control me-2" type="submit" value="로그아웃"></input>
            </form></a></div>
      
        <form class="container-fluid justify-content-start">
        <li class="nav-item">
          <a href="{% url "accounts:update" %}"><button class="btn btn-outline-light">회원정보수정</button></a>
      <li>
       </form>
      {% else %}
        
          <a class="nav-link" href="{% url 'accounts:login' %}"><button class="btn btn-outline-light">로그인</button></a>
      
         
          <a class="nav-link" href="{% url "accounts:signup" %}"><button class="btn btn-outline-light">회원가입</button></a>
       
        
    
    {% endif %}     
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      </ul>
    </div>
  </div>


        

    
</nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>