accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("follow/<int:user_id>/", views.follow, name="follow"),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path("",views.post_list, name="list"),
    path("<int:pk>/",views.post_detail, name="detail"),
    path("create/",views.create, name="create"),
    path("update/<int:pk>",views.update, name="update"),
    path("delete/<int:pk>",views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:pk>/check/", views.check, name="check"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('products.urls')),
    path("accounts/", include("accounts.urls")),
]

products/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    price = models.PositiveIntegerField()
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    check_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="check_posts")

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    content = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

products/forms.py
from django import forms
from products import models
from .models import Post, Comment
class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = "__all__"
        exclude = ['author', 'check_users']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ("post", "user")

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST


# Create your views here.


def post_list(request):
    posts = Post.objects.all()
    context = {
        "posts": posts,
    }
    return render(request, "products/list.html", context)


def post_detail(request, pk):
    posts = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    comments = posts.comments.all().order_by("-pk")
    context = {
        "posts": posts,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, "products/detail.html", context)



def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("post:detail", post.id)
    else:
        form = PostForm()
    context = {"form": form}
    return render(request, "products/create.html", context)

@login_required
@require_POST
def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated:
        if post.author == request.user:
            post = get_object_or_404(Post, pk=pk)
            post.delete()
    return redirect("post:list")

@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                article = form.save()
                return redirect("post:detail", post.id)
        else:
            form = PostForm(instance=post)
    else:
        return redirect("post:list")

    context = {
        "form": form,
        "post": post,
    }
    return render(request, "products/update.html", context)

@require_POST
def comment_create(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.user = request.user

        # comment.post_id = pk
        # print("comment.post_id:", comment.post_id)
        comment.save()

        return redirect("post:detail", post.pk)


@require_POST
def comment_delete(request, pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
    return redirect("post:detail", pk)


@require_POST
def check(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if post.check_users.filter(pk=request.user.pk).exists():
            post.check_users.remove(request.user)  # 찜 취소
        else:
            post.check_users.add(request.user)  # 찜
        return redirect("post:list")
    return redirect("accounts:login")

products/templates/products/create.html
{% extends "base.html" %}

{% block content %}
    <br><br>
<h2>새 글 작성</h2>

<form action="{% url 'post:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button class="btn btn-outline-dark" type="submit" >저장</button>
     <a href="{% url "post:list" %}">
    <button class="btn btn-outline-dark" type="button" >목록으로</button></a>

    </div>

</form>




{% endblock content %}

products/templates/products/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<br><br><h1>{{ posts.title }}</h1><br><br>
    <div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="{% static "products/13.png" %}" class="d-block w-50" alt="판매자 사진이였던 것">
    </div>
    <div class="carousel-item">
       <img src="{% static "products/14.png" %}" class="d-block w-50" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "products/15.png" %}" class="d-block w-50" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<p>작성자: {{ posts.author.username }}</p>

<p>가격: {{ posts.price }} 원</p>
<div>
<p>내용: {{ posts.content }}</p>
    {% if posts.image %}
        <img src="{{ products.image.url }}">
    {% endif %}

</div>

    {% if user == posts.author %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'post:update' posts.id %}"><button class="btn btn-outline-dark" type="submit" >글수정</button></a>


        <form action="{% url 'post:delete' posts.id %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-outline-dark" type="submit" value="삭제">
        </form></div>
    {% endif %}

<p> {{ posts.updated_at }} 에 최종 수정됨</p><br>
   <a href="{% url "post:list" %}">
        <button class="btn btn-outline-dark" type="button" >목록으로</button></a>
<a href="{% url "accounts:profile" posts.author.id %}"><button type="button" class="btn btn-outline-dark">작성자 "{{ posts.author.username }}" 의 프로필페이지</button></a>



    {% if request.user.is_authenticated %}
    <br>
    <hr>
    <h3>댓글 {{ comments|length }}개</h3>
    <form action="{% url "post:comment_create" posts.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <input class="btn btn-outline-dark" type="submit" value="댓글작성">
        </div>
    </form>
    {% endif %}

    {% for comment in comments %}

        <ul><br>
        <li>{{ comment.content }} - {{ comment.user.username }}</li><br>

        {% if user == comment.user %}
        <form action="{% url "post:comment_delete" posts.pk comment.pk%}" method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <input class="btn btn-outline-dark" type="submit" value="삭제"></div>
        </form>
        {% endif %}

        </ul>

    {% empty %}
    <p>댓글이 없습니다.</p>

    {% endfor %}
{% endblock content %}

products/templates/products/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br>
{% if request.user.is_authenticated %}
    <a href="{% url 'post:create' %}">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button class="btn btn-outline-dark" type="button" >글 작성하기</button>
    </div>

    </a>
{% else %}
    <h3><span class="badge text-bg-secondary">Notifications</span> <a href="{% url "accounts:login" %}">게시글을 작성하시려면 여기를 눌러 로그인하세요 </a></h3>
    <br>
    <br>
{% endif %}
{% for post in posts %}

  <div class="col">
<div class="card" style="width: 18rem; text-align: center">
  <img src="{% static "products/12.png" %}" class="card-img-top" alt="게시자가 올린 제품의 사진 이였던 것">
  <div class="card-body">
    <h5 class="card-title"><a href="{% url 'post:detail' post.id %}">{{ post.title }} </a></h5>
    <p class="card-text"><br>{{ post.content }}<br></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> {{ post.price }} 원</li>
    <li class="list-group-item"> {{ post.auther }} 작성자</li>
  </ul>
  <div class="card-body">
    <a class="card-link"><form action="{% url "post:check" post.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in post.check_users.all %}
                    <input class="btn btn-outline-dark" type="submit" value="찜하기 취소">
                {% else %}
                    <input class="btn btn-outline-dark" type="submit" value="찜하기">
                {% endif %}
            </form></a>
  </div>

  </div>
<br><br><br>
</div>
{% endfor %}
{% endblock content %}

products/templates/products/update.html
{% extends "base.html" %}

{% block content %}
<h2>Edit Post</h2>

<form action="{% url "post:update" post.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">저장</button>
</form>

<a href="{% url "post:detail" post.id %}">이전으로</a>
{% endblock content %}